menu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'', include('myApp.urls', namespace='myApp')),
    # url(r'^search/', include('haystack.urls'))
]

myApp/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views
from myApp.views import RegisterView, UserActiveView, LoginView, \
    Base1View, BaseView, IndexView, \
    MenuView, DishView, \
    IngrePriceView, IngreShowView, IngreDescsView, IngreDetailsView,\
    HealthView, HealthArticleView, \
    CommunityView, \
    UserCreateView, UserCollectionView, UserCommentView, UserCartView, UserOderView, CartUpdateView, CartAddView, CartDeleteView


# app_name = 'myApp'

urlpatterns = [
    url('^login/$', LoginView.as_view(), name='login'),
    url('^register/$', RegisterView.as_view(), name='register'),
    url('^user/active/(?P<token>.*)/$', UserActiveView.as_view(), name='userActive'),

    url('^base/$', BaseView.as_view(), name='base'),
    url('^base1/$', Base1View.as_view(), name='base1'),
    url('^index/$', IndexView.as_view(), name='index'),

    url('^menu/$', MenuView.as_view(), name='menu1'),
    url('^menu/(\w+)/$', MenuView.as_view(), name='menu2'),
    url('^menu/(\w+)/(\w+)/$', MenuView.as_view(), name='menu3'),
    url('^menu/(\w+)/(\w+)/(\d+)/$', MenuView.as_view(), name='menu4'),
    url('^dish/(\d+)/$', DishView.as_view(), name='dish'),

    url('^ingre/$', IngrePriceView.as_view(), name='ingre'),
    url('^ingre/price/$', IngrePriceView.as_view(), name='ingre_price'),
    url('^ingre/show/$', IngreShowView.as_view(), name='ingre_show'),
    url('^ingre/descs/$', IngreDescsView.as_view(), name='ingre_descs'),
    url('^ingre/details/$', IngreDetailsView.as_view(), name='ingre_details'),
    url('^ingre/price/(\w+)/$', IngrePriceView.as_view(), name='ingre_price2'),
    url('^ingre/show/(\w+)/$', IngreShowView.as_view(), name='ingre_show2'),
    url('^ingre/descs/(\w+)/$', IngreDescsView.as_view(), name='ingre_descs2'),
    url('^ingre/details/(\w+)/$', IngreDetailsView.as_view(), name='ingre_details2'),

    url('^health/$', HealthView.as_view(), name='health1'),
    url('^health/(\d+)/$', HealthView.as_view(), name='health2'),
    url('^health/(\d+)/(\d+)$', HealthView.as_view(), name='health3'),
    url('^health/article/(\d+)$', HealthArticleView.as_view(), name='health_article'),

    url('^community/$', CommunityView.as_view(), name='community'),

    url('^user/$', UserCreateView.as_view(), name='user'),
    url('^user/create/$', UserCreateView.as_view(), name='user_create'),
    url('^user/create/(\d+)/$', UserCreateView.as_view(), name='user_create2'),
    url('^user/collection/$', UserCollectionView.as_view(), name='user_collection'),
    url('^user/collection/(\d+)/$', UserCollectionView.as_view(), name='user_collection2'),
    url('^user/comment/$', UserCommentView.as_view(), name='user_comment'),
    url('^user/cart/$', UserCartView.as_view(), name='user_cart'),
    url('^user/order/$', UserOderView.as_view(), name='user_order'),
    url('^add/$', CartAddView.as_view(), name='cart_add'),
    url('^update/$', CartUpdateView.as_view(), name='cart_update'),
    url('^delete/$', CartDeleteView.as_view(), name='cart_delete'),
    # url('^addimg/$', views.add)
    # url('^collection/$', Collection.as_view(), name='collection'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # url('^uploadImg/$', views.uploadImg),
    # url('^showImg/$', views.showImg),

myApp/models.py
from django.db import models


# Create your models here.


from django.db.models.fields.files import ImageFieldFile
import time


# 菜品表
class Dish(models.Model):
    name = models.CharField(u'名字', max_length=25)
    img = models.ImageField(u'图片', upload_to='dish')
    descs = models.TextField(u'描述', null=True)
    details = models.TextField(u'小窍门', null=True)
    addTime = models.DateField(default='2019-02-26')
    number = models.IntegerField(u'收藏数', null=True, default=0)
    is_show = models.BooleanField(default=False)

    user = models.ForeignKey('User', default=1, on_delete=models.CASCADE)
    skill = models.ForeignKey('Skill', default=1, on_delete=models.CASCADE)
    taste = models.ForeignKey('Taste', default=1, on_delete=models.CASCADE)
    degree = models.ForeignKey('Degree', default=1, on_delete=models.CASCADE)
    time = models.ForeignKey('Time', default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'dish'
        unique_together = ("name", "img")


# 菜品_工艺表
class Skill(models.Model):
    name = models.CharField(u'工艺名', max_length=5)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'dish_skill'


# 菜品_口味表
class Taste(models.Model):
    name = models.CharField(u'口味名', max_length=5)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'dish_taste'


# 菜品_时间表
class Time(models.Model):
    name = models.CharField(u'所需时间', max_length=5)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'dish_time'


# 菜品_难度
class Degree(models.Model):
    name = models.CharField(u'难度', max_length=5)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'dish_degree'


# 菜品_步骤表
class Step(models.Model):
    textStep1 = models.CharField(u'步骤序号', max_length=5, default=1)
    textStep2 = models.TextField(u'步骤内容')
    imgStep = models.ImageField(u'步骤图片', upload_to='dishStep')
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = 'dish_Step'
        # unique_together = ("textStep1", "imgStep")


# 菜品_主料表
class Main(models.Model):
    name = models.CharField(max_length=10, default="主料名")
    number = models.CharField(max_length=10)
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = 'dish_main'


# 菜品_辅料表
class Auxi(models.Model):
    name = models.CharField(max_length=10, default="辅料名")
    number = models.CharField(max_length=10)
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = 'dish_auxi'


# 菜品_一级分类表
class Dish_Cate(models.Model):
    name = models.CharField(u'分类名', max_length=10)
    dish_cate2 = models.ForeignKey('Dish_Cate2', on_delete=models.CASCADE)
    cate_dish = models.ManyToManyField(Dish, through='Menu', related_name='cateDish')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'dish_cate'


# 菜品_二级分类表
class Dish_Cate2(models.Model):
    name = models.CharField(u'分类名', max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Dish_Cate2'


# 食材表
class Ingre(models.Model):
    name = models.CharField(u'食材名', max_length=10, unique=True)
    img = models.ImageField(u'图片', upload_to='ingre')
    descs = models.TextField(u'选购技巧', null=True)
    details = models.TextField(u'营养功效', null=True)
    price = models.IntegerField(u'价格', null=True, default=30)
    is_show = models.BooleanField(default=False)
    create = models.ManyToManyField(Dish, through='CreateDish', related_name='createDish')
    cate = models.ForeignKey('Ingre_Cate', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Ingre'


# 食材_分类表
class Ingre_Cate(models.Model):
    name = models.CharField(u'分类名', max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Ingre_Cate'


# 用户表
class User(models.Model):
    name = models.CharField(u'姓名', max_length=25, unique=True)
    img = models.ImageField(u'头像', default="img/user.png", upload_to='img')
    email = models.EmailField(u'邮箱', max_length=25, unique=True)
    password = models.CharField(u'密码', max_length=25)
    address = models.CharField(u'地址', default='暂无地址', max_length=50)
    addTime = models.DateTimeField(u'创建时间', auto_now_add=True)
    is_active = models.IntegerField(u'是否激活', default=0)

    user_collection = models.ManyToManyField(Dish, through='Collection',  related_name='userCollection')
    user_comment = models.ManyToManyField(Dish, through='Comment', related_name='userComment')
    user_cart = models.ManyToManyField(Ingre, through='Cart', related_name='userCart')
    user_oder = models.ManyToManyField(Ingre, through='Order', related_name='userOrder')
    user_feedback = models.ManyToManyField(Ingre, through='Feedback', related_name='userFeedback')
    user_Community = models.ManyToManyField(Dish, through='Community',  related_name='userCommunity')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'
        db_table = 'user'


#文章表
class Article(models.Model):
    title = models.CharField(u'文章名', max_length=50)
    img = models.ImageField(u'插图', upload_to='article')
    details = models.TextField(u'正文')
    is_show = models.BooleanField(default=False)
    article_cate = models.ForeignKey('Article_Cate', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'article'


# 文章分类表
class Article_Cate(models.Model):
    name = models.CharField(u'文章分类', max_length=10)
    img = models.ImageField(u'插图', default='articleCate/1.png', upload_to='articleCate')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'article_cate'


# @1菜品一级分类与菜品对应表
class Menu(models.Model):
    dish_cate = models.ForeignKey('Dish_Cate', on_delete=models.CASCADE)
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = 'Menu'
        unique_together = ("dish_cate", "dish")


# @2原料与菜品对应表
class CreateDish(models.Model):
    ingre = models.ForeignKey('ingre', on_delete=models.CASCADE)
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = 'createdish'


# @3收藏表（用户与菜品）
class Collection(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = 'collection'


# @4菜品评论表（用户与菜品）
class Comment(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)
    comment = models.CharField(max_length=255)
    addTime = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'comment'


# @5购物车表（用户与食材）
class Cart(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    ingre = models.ForeignKey('Ingre', on_delete=models.CASCADE)

    class Meta:
        db_table = 'cart'


# @6订单表（用户与食材）
class Order(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    ingre = models.ForeignKey('Ingre', on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    amount = models.IntegerField(default=0)

    class Meta:
        db_table = 'order'


# @7用户反馈表（用户与食材）
class Feedback(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    ingre = models.ForeignKey('Ingre', on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)

    class Meta:
        db_table = 'feedback'


# @8美食社区表（用户与菜品）
class Community(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    dish = models.ForeignKey('Dish', on_delete=models.CASCADE, default=1)

    class Meta:
        db_table = 'community'


# 图片试验表
class Img(models.Model):
    img_url = models.ImageField(upload_to='img', max_length=255)


class demo(models.Model):
    text11 = models.TextField()
    addTime = models.DateField(auto_now_add=True, null=True)

    class Meta:
        db_table = 'demo'

templates/myApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="icon" href="data:image/ico;base64,aWNv">

    <link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}" />


    <script type="text/javascript" charset="UTF-8" src="{% static 'base/js/base.js' %}"></script>
    {% block cssjs %}

    {% endblock cssjs %}
</head>
<body>
    <header>
        <div id="header1">
            <div id="header1_form">
                <form class="search" method="get" action="/search/" >

                    <input class="input1" type="text" placeholder="请输入菜单/食材/作者" name="q" />
                    <input class="input2" type="submit" value="搜索" />
                </form>
            </div>
            {% if request.user.is_authenticated %}
                <div id="header1_a">
                    <a href="#">{{ request.user.username }}</a>
                    <a href="#">退出登录</a>
                </div>
            {% else %}
                <div id="header1_a">
                    <a href="#">登录</a>
                    <a href="#">注册</a>
                </div>
            {% endif %}


        </div>
        <div id="header2">
            <div id="ul">
                <ul>
                    <li><a href="#"><strong>首页</strong></a></li>
                    <li class="li1" onmouseover="appearMenu()" onmouseout="disappearMenu()">
                        <a href="#"><strong>菜单分类</strong>》》</a>
                        <div id="header2_menu">
                            <div id="table">
                                <ul>
                                {% for obj1 in dish_cate2 %}
                                    <li class="li1"><a href="#">{{ obj1.name }}</a></li>
                                    <li class="li2">
                                    {% for obj2 in obj1.dish_cate_set.all|slice:":7" %}
                                        <a href="#">{{ obj2.name }}</a>
                                    {% endfor %}
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                            <div id="header2_menu_img">
                                <img src="{% static "base/img/6.jpg" %}" width="250px" height="250px">
                            </div>
                        </div>
                    </li>
                    <li class="li2" onmouseover="appearMate()" onmouseout="disappearMate()">
                        <a href="#"><strong>食材大全</strong>》》</a>
                        <div id="header2_material">
                            <div id="table2">
                                <ul>
                                {% for obj1 in ingre_cate %}
                                    <li class="li1"><a href="#">{{ obj1.name }}</a></li>
                                    <li class="li2">
                                    {% for obj2 in obj1.ingre_set.all|slice:":7" %}
                                        <a href="#">{{ obj2.name }}</a>
                                    {% endfor %}
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                            <div id="header2_material_img">
                                <img src="{% static "base/img/6.jpg" %}" width="250px" height="250px">
                            </div>
                        </div>
                    </li>
                    <li><a href="#"><strong>健康咨讯</strong></a></li>
                    <li><a href="#"><strong>美食社区</strong></a></li>
                </ul>
            </div>
        </div>
    </header>
    <div id="aside">
        {% block aside %}
{#            {% for obj in dish_cate2 %}#}
{#                {% for obj2 in obj.dish_cate_set.all|slice:":2" %}#}
{#                    {{ obj2.name }}#}
{#                {% endfor %}#}
{##}
{#            {% endfor %}#}
{#            {% for dish_cate2 in dish_cate2|slice:":1" %}#}
{#                {{ dish_cate2.name }}#}
{#            {% endfor %}#}






        {% endblock aside %}
    </div>
    <footer></footer>
</body>
</html>

templates/myApp/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="icon" href="data:image/ico;base64,aWNv">

    <link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}" />


    <script type="text/javascript" charset="UTF-8" src="{% static 'base/js/base.js' %}"></script>
    {% block cssjs %}

    {% endblock cssjs %}
</head>
<body>
    <header>
        <div id="header1">
            <div id="header1_form">
                <form class="search" method="get" action="/search/" >

                    <input class="input1" type="text" placeholder="请输入菜单/食材/作者" name="q" />
                    <input class="input2" type="submit" value="搜索" />
                </form>
            </div>
            {% if request.user.is_authenticated %}
                <div id="header1_a">
                    <a href="/user/">{{ request.user.username }}</a>
                    <a href="#">退出登录</a>
                </div>
            {% else %}
                <div id="header1_a">
                    <a href="/login/">登录</a>
                    <a href="/register/">注册</a>
                </div>
            {% endif %}


        </div>
        <div id="header2">
            <div id="ul">
                <ul>
                    <li><a href="/index/"><strong>首页</strong></a></li>
                    <li class="li1" onmouseover="appearMenu()" onmouseout="disappearMenu()">
                        <a href="/menu/"><strong>菜单分类</strong>》》</a>
                        <div id="header2_menu">
                            <div id="table">
                                <ul>
                                {% for obj1 in dish_cate2 %}
                                    <li class="li1"><a href="/menu/">{{ obj1.name }}</a></li>
                                    <li class="li2">
                                    {% for obj2 in obj1.dish_cate_set.all|slice:":7" %}
                                        <a href="/menu/{{ obj1.name }}/{{ obj2.name }}/">{{ obj2.name }}</a>
                                    {% endfor %}
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                            <div id="header2_menu_img">
                                <img src="{% static "base/img/6.jpg" %}" width="250px" height="250px">
                            </div>
                        </div>
                    </li>
                    <li class="li2" onmouseover="appearMate()" onmouseout="disappearMate()">
                        <a href="/ingre/"><strong>食材大全</strong>》》</a>
                        <div id="header2_material">
                            <div id="table2">
                                <ul>
                                {% for obj1 in ingre_cate %}
                                    <li class="li1"><a href="#">{{ obj1.name }}</a></li>
                                    <li class="li2">
                                    {% for obj2 in obj1.ingre_set.all|slice:":7" %}
                                        <a href="#">{{ obj2.name }}</a>
                                    {% endfor %}
                                    </li>
                                {% endfor %}
                                </ul>
                            </div>
                            <div id="header2_material_img">
                                <img src="{% static "base/img/7.jpg" %}" width="250px" height="250px">
                            </div>
                        </div>
                    </li>
                    <li><a href="/health/"><strong>健康咨讯</strong></a></li>
                    <li><a href="/community/"><strong>美食社区</strong></a></li>
                </ul>
            </div>
        </div>
    </header>
    <div id="aside">
        {% block aside %}
{#            {% for obj in dish_cate2 %}#}
{#                {% for obj2 in obj.dish_cate_set.all|slice:":2" %}#}
{#                    {{ obj2.name }}#}
{#                {% endfor %}#}
{##}
{#            {% endfor %}#}
{#            {% for dish_cate2 in dish_cate2|slice:":1" %}#}
{#                {{ dish_cate2.name }}#}
{#            {% endfor %}#}






        {% endblock aside %}
    </div>
    <footer></footer>
</body>
</html>

templates/myApp/dish.html
{% extends 'myApp/base1.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% block cssjs %}

        <link rel="stylesheet" type="text/css" href="{% static 'menu/css/dish.css' %}" />
{#        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>#}
        <script type="text/javascript" src="{% static 'base/js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript">
            $(function () {
                $('#a').click(function () {
                    dish_id = $(this).attr('dish_id')
                    csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    params = {
                        'dish_id': dish_id,
                        'csrfmiddlewaretoken': csrf
                    }

                    $.post('/user/collection/', params, function (data) {
                        if(data.res == 1){
                            $('#a').find('img').attr('src', "{% static 'menu/img/collect (2).png' %}")
                        }else {
                            $('#a').find('img').attr('src', "{% static 'menu/img/collect (1).png' %}")
                        }

                    })
                })
            })
        </script>
    {% endblock cssjs %}
</head>
<body>


    {% block aside %}
        <div id="description">
            <div id="img">
                <img src="{{ dish.img.url }}" width="300px" height="400">
            </div>
            <div id="introduce">
                <div id="name" class="div">
                    {% csrf_token %}
                    <span>{{ dish.name }}</span>
                    {% if dish.id in dish_id_list %}
                        <a id="a" href="javascript:;" dish_id="{{ dish.id }}"><img src="{% static 'menu/img/collect (2).png' %}" width="45px" height="45px;"></a>
                    {% else %}
                        <a id="a" href="javascript:;" dish_id="{{ dish.id }}"><img src="{% static 'menu/img/collect (1).png' %}" width="45px" height="45px;"></a>
                    {% endif %}
                </div>
                <div id="other" class="div">
                    <ul>
                        <li id="li1">
                            <span class="span1">工艺</span>
                            <span class="span2">{{ dish.skill }}</span>
                        </li>
                        <li id="li2">
                            <span class="span1">口味</span>
                            <span class="span2">{{ dish.taste }}</span>
                        </li>
                        <li id="li3">
                            <span class="span1">难度</span>
                            <span class="span2">{{ dish.degree }}</span>
                        </li>
                        <li id="li4">
                            <span class="span1">时间</span>
                            <span class="span2">{{ dish.time }}</span>
                        </li>
                    </ul>
                </div>
                <div id="word" class="div">
                    <p>
                        {{ dish.descs }}
                    </p>
                </div>
            </div>
        </div>

        <div id="ingredient">
            <div id="main">
                <h3>主料</h3>
                <ul>
                    {% for mainObj in main %}
                        <li>
                            <a class="text" href="{% url 'myApp:ingre_price2' mainObj.name %}">{{ mainObj.name }}</a>
                            <span>{{ mainObj.number }}</span>
                            <a class="img" href="{% url 'myApp:ingre_price2' mainObj.name %}"><img src="{% static 'menu/img/shopping1.png' %}" width="50px", height="30px", alt="加入购物车"></a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div id="auxi">
                <h3>辅料</h3>
                <ul>
                    {% for auxiObj in auxi %}
                        <li>
                            <a class="text" href="{% url 'myApp:ingre_price2' auxiObj.name %}">{{ auxiObj.name }}</a>
                            <span>{{ auxiObj.number }}</span>
                            <a class="img" href="{% url 'myApp:ingre_price2' auxiObj.name %}"><img src="{% static 'menu/img/shopping1.png' %}" width="50px", height="30px", alt="加入购物车"></a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div id="stepAddi">
            <h2>{{ dish.name }}的做法</h2>
            {% for stepObj in step %}
                <div class="step">
                <div class="img"><img src="{{ stepObj.imgStep.url }}" width="300px" height="300px"></div>
                <div class="text">
                    <h4><em>{{ stepObj.textStep1 }}</em></h4>
                    <p>{{ stepObj.textStep2 }}</p>
                </div>
            </div>
            {% endfor %}
            <h2>小窍门</h2>
            <div id="addition">
                <p>{{ dish.details }}</p>
            </div>
        </div>
        <div id="comment">
            <h2>{{ dish.name }}的评论</h2>

            <div class="comment">
                {% if request.user.is_authenticated %}
                    <a href="#"><img src="{{ user.img.url }}" width="50px" height="50px"></a>
                    <form method="post" action="{% url 'myApp:dish' dish.id %}">
                        {% csrf_token %}
                        <textarea placeholder="说点什么" name="comment"></textarea>
                        <input type="hidden" name="dish_id" value="{{ dish.id }}"/>
                        <input type="submit" name="submit" value="提交" />
                    </form>
                {% endif %}
                <div id="commentShow">
                    <ul>
                        {% for comment in commentAll %}
                            <li>
                                <a href="#">
                                    <img src="{{ comment.user.img.url}}" width="50px" height="50px">
                                    <h5>{{ comment.user.name }}</h5>
                                </a>
                                <div id="commentShow1">
                                    <p>{{ comment.comment }}</p>
                                    <span>{{ comment.addTime }}</span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    {% endblock aside %}
</body>
</html>

templates/myApp/ingre.html
{% extends 'myApp/base1.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% block cssjs %}
            <link rel="stylesheet" type="text/css" href="{% static 'menu/css/menu.css' %}" />
    {% endblock cssjs %}

    {% block ingrecss %}

    {% endblock %}
</head>
<body>


    {% block aside %}
        <div id="top">
            <div id="img">
                <img src='../img/2.jpg' alt="猪肉" width="80px" height="80px">
            </div>
            <div id="text">
                <span id="span1">猪肉</span>
                <br>
                <span id="span2">为你介绍猪肉的技巧和营养功效，有122种做法供你参考，同时提供购买需求</span>
            </div>
        </div>
        <div id="middle">
            <ul>

                <li><a href="/ingre/price/{{ ingre.name }}">{{ ingre.name }}的购买</a></li>
                <li><a href="/ingre/show/{{ ingre.name }}">{{ ingre.name }}的做法</a></li>
                <li><a href="/ingre/descs/{{ ingre.name }}">选购技巧</a></li>
                <li><a href="/ingre/details/{{ ingre.name }}">营养功效</a></li>

            </ul>
        </div>
        <div id="bottom">
            {% block ingre %}
            {% endblock %}
        </div>

    {% endblock aside %}
</body>
</html>